name: firebase_chat_app
description: "A new Flutter project."

publish_to: 'none'



environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  gap: ^3.0.1
  permission_handler: ^12.0.1
  image_picker: ^1.2.0
  shimmer: ^3.0.0
  device_info_plus: ^11.5.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1

  #------------ rive animations ------------#
  rive: ^0.13.20

  #----------- network -----------#
  network:
    path: network


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  #----------- auto generators -----------#
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.11.0


  #----------- asset generator configuration ----------#
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: nunito-sans
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito_sans/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito_sans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito_sans/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito_sans/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito_sans/NunitoSans-Black.ttf
          weight: 900
