name: network
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  cross_file: ^0.3.4+2
  flutter_image_compress: ^2.4.0
  quiver: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
